# Generated by Django 5.1.5 on 2025-07-21 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine_backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpotlightArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image_url', models.URLField()),
                ('article_url', models.URLField()),
                ('summary', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
