# Generated by Django 5.1.5 on 2025-07-21 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine_backend', '0002_spotlightarticle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spotlightarticle',
            name='article_url',
        ),
        migrations.RemoveField(
            model_name='spotlightarticle',
            name='image_url',
        ),
        migrations.AddField(
            model_name='spotlightarticle',
            name='description',
            field=models.TextField(default='Default description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spotlightarticle',
            name='image',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='spotlightarticle',
            name='slug',
            field=models.SlugField(default='Default', unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='spotlightarticle',
            name='summary',
            field=models.TextField(default=''),
        ),
    ]
