# Generated by Django 5.1.5 on 2025-07-21 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magazine_backend', '0003_remove_spotlightarticle_article_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spotlightarticle',
            old_name='image',
            new_name='image_url',
        ),
    ]
