# Generated by Django 5.1.5 on 2025-07-21 15:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine_backend', '0004_rename_image_spotlightarticle_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotlightarticle',
            name='published_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
