# Generated by Django 5.1.5 on 2025-07-21 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine_backend', '0005_spotlightarticle_published_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotlightarticle',
            name='article_url',
            field=models.URLField(default=''),
        ),
    ]
