# Generated by Django 5.1.5 on 2025-07-21 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magazine_backend', '0006_spotlightarticle_article_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SpotlightArticle',
        ),
    ]
