# Generated by Django 5.1.5 on 2025-08-11 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magazine_backend', '0007_delete_spotlightarticle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='published_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='article',
            name='image_url',
        ),
    ]
