# Generated by Django 5.1.5 on 2025-08-11 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine_backend', '0008_rename_published_at_article_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrendingArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=300)),
                ('subheadline', models.CharField(blank=True, max_length=500)),
                ('image_url', models.URLField(max_length=500)),
                ('eyebrow', models.CharField(blank=True, max_length=300)),
                ('author', models.CharField(default='No Author Mentioned', max_length=200)),
                ('article_date', models.CharField(max_length=100)),
            ],
        ),
    ]
