# Generated by Django 5.1.5 on 2025-08-12 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine_backend', '0009_trendingarticle'),
    ]

    operations = [
        migrations.AddField(
            model_name='trendingarticle',
            name='article_data',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='trendingarticle',
            name='article_headings',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='trendingarticle',
            name='article_image',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='trendingarticle',
            name='article_link',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='trendingarticle',
            name='original_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
