# Generated by Django 5.1.5 on 2025-08-14 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine_backend', '0012_tvshowsarticle'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(blank=True, max_length=255)),
                ('subheadline', models.CharField(blank=True, max_length=255)),
                ('image_url', models.URLField(blank=True)),
                ('eyebrow', models.CharField(blank=True, max_length=255)),
                ('author', models.CharField(blank=True, max_length=255)),
                ('article_date', models.CharField(blank=True, max_length=50)),
                ('article_data', models.TextField(blank=True)),
                ('article_link', models.URLField(blank=True)),
                ('original_url', models.URLField(blank=True)),
                ('article_image', models.URLField(blank=True)),
                ('article_headings', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'homepage_article',
            },
        ),
        migrations.CreateModel(
            name='MoviesArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(blank=True, max_length=255)),
                ('subheadline', models.CharField(blank=True, max_length=255)),
                ('image_url', models.URLField(blank=True)),
                ('eyebrow', models.CharField(blank=True, max_length=255)),
                ('author', models.CharField(blank=True, max_length=255)),
                ('article_date', models.CharField(blank=True, max_length=50)),
                ('article_data', models.TextField(blank=True)),
                ('article_link', models.URLField(blank=True)),
                ('original_url', models.URLField(blank=True)),
                ('article_image', models.URLField(blank=True)),
                ('article_headings', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'movies_article',
            },
        ),
    ]
